language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install
  - mysql -e 'create database blog;'
  - mysql -u root blog < tests/testdatabasesetup.sql

script: vendor/bin/phpunit